sudo: required

language: python

services:
  - docker

python:
    - "2.7"

install: "pip install -r requirements.txt"

script: 
  - python tests.py

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t shaobol/flask:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID . 
  - docker push shaobol/flask:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID;