sudo: required

language: python

services:
  - docker

python:
    - "2.7"

install: "pip install -r requirements.txt"

script: 
  - python tests.py

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.cn-hangzhou.aliyuncs.com;
  - docker build -t registry.cn-hangzhou.aliyuncs.com/mkdef/flask:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID . 
  - docker push registry.cn-hangzhou.aliyuncs.com/mkdef/flask:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID;